{
  "openapi": "3.0.0",
  "info": {
    "title": "Users Management API",
    "description": "API for users management. Create, list, update, show user profile and turn users into admins",
    "version": "0.4.0"
  },
  "paths": {
    "/users": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Returns a list of all registered users",
        "description": "Only **admin users** can list users",
        "parameters": [
          {
            "in": "header",
            "name": "user_id",
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "required": "true",
            "description": "A string on format uuid representing a user id"
          }
        ],
        "responses": {
          "200": {
            "description": "An array of users objects",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/User"
                  },
                  "example": [
                    {
                      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                      "name": "string",
                      "admin": false,
                      "email": "user@example.com",
                      "created_at": "2021-11-15T22:10:38.819Z",
                      "updated_at": "2021-11-15T22:10:38.819Z"
                    },
                    {
                      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                      "name": "string",
                      "admin": false,
                      "email": "user@example.com",
                      "created_at": "2021-11-15T22:10:38.819Z",
                      "updated_at": "2021-11-15T22:10:38.819Z"
                    },
                    {
                      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                      "name": "string",
                      "admin": true,
                      "email": "user@example.com",
                      "created_at": "2021-11-15T22:10:38.819Z",
                      "updated_at": "2021-11-15T22:10:38.819Z"
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "A bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Creates a user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "format": "email"
                  }
                },
                "required": [
                  "name",
                  "email"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                  "name": "string",
                  "admin": false,
                  "email": "user@example.com",
                  "created_at": "2021-11-15T22:10:38.819Z",
                  "updated_at": "2021-11-15T22:10:38.819Z"
                }
              }
            }
          },
          "400": {
            "description": "A bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}/admin": {
      "patch": {
        "tags": [
          "Users"
        ],
        "summary": "Turns a user into an admin user",
        "parameters": [
          {
            "in": "path",
            "name": "user_id",
            "description": "The user id",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                  "name": "string",
                  "admin": true,
                  "email": "user@example.com",
                  "created_at": "2021-11-15T22:10:38.819Z",
                  "updated_at": "2021-11-15T22:10:38.819Z"
                }
              }
            }
          },
          "404": {
            "description": "User not found or others errors",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Returns a user object",
        "description": "Returns a user profile",
        "parameters": [
          {
            "in": "path",
            "name": "user_id",
            "description": "The user id",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "404": {
            "description": "User not found or others errors",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Error": {
        "type": "object",
        "properties": {
          "error": {
            "type": "string",
            "example": "Some API error"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "name": {
            "type": "string"
          },
          "admin": {
            "type": "boolean"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      }
    }
  }
}